command: ["python", "app.py"]

resources:
  - name: DATABASE_URL
    secret:
      scope: support_app_secrets
      key: DATABASE_URL
  - name: MASSIVE_API_KEY
    secret:
      scope: support_app_secrets
      key: MASSIVE_API_KEY

env:
  - name: DATABASE_URL
    valueFrom: ${resources.DATABASE_URL}
  - name: MASSIVE_API_KEY
    valueFrom: ${resources.MASSIVE_API_KEY}
